brew 'coreutils'
brew 'pandoc'
brew 'synchronal/tap/medic-bash'
brew 'synchronal/tap/medic-ext-homebrew'
brew 'synchronal/tap/medic-ext-rust'
brew 'synchronal/tap/medic-ext-tool-versions'
brew 'synchronal/tap/medic-rs'
